# Via Getting Started info
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: 'cimg/node:14'
    steps:
      - browser-tools/install-chrome
      - node/test
