# Via Getting Started info
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1
  node: circleci/node@3.0.0

# Based on source from https://circleci.com/orbs/registry/orb/circleci/node?version=3.0.0#commands-install-packages
# DEV: Was burning through time on features that felt experimental (orbs) so moving to more familiar setup
jobs:
  parameters:
    docker-image:
      type: string
  build:
    docker:
      - image: << parameters.docker-image >>
    steps:
      - checkout
      - node/install-packages
      - run:
          # https://in.mathworks.com/matlabcentral/answers/385952-why-do-i-see-error-while-loading-shared-libraries-libxss-so-1-when-starting-matlab-on-a-linux-mac
          name: Install Electron dependencies
          command: sudo apt-get install libxss1
      - run:
          name: Run NPM Tests
          command: npm test

# Run multiple Node.js version tests
# https://gist.github.com/felicianotech/481297bc3db4d6c22ed2490f86e88190
workflows:
  matrix-tests:
    jobs:
      - build:
          docker-image: "circleci/node:14-browsers-legacy"
      - build:
          docker-image: "circleci/node:12-browsers-legacy"
      - build:
          docker-image: "circleci/node:10-browsers-legacy"
