# Based on Getting Started prompt
#   source from https://circleci.com/orbs/registry/orb/circleci/node?version=3.0.0#commands-install-packages
#   and https://gist.github.com/felicianotech/481297bc3db4d6c22ed2490f86e88190
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1
  node: circleci/node@3.0.0

jobs:
  build:
    parameters:
      docker-image:
        type: string
    docker:
      - image: << parameters.docker-image >>
    steps:
      - checkout
      - node/install-packages
      - run:
          # https://in.mathworks.com/matlabcentral/answers/385952-why-do-i-see-error-while-loading-shared-libraries-libxss-so-1-when-starting-matlab-on-a-linux-mac
          name: Install Electron dependencies
          command: sudo apt-get install libxss1
      - run:
          name: Run NPM Tests
          command: npm test

# Run multiple Node.js version tests
workflows:
  matrix-tests:
    jobs:
      # DEV: We could also use `matrix` as defined here: https://circleci.com/docs/2.0/configuration-reference/#matrix-requires-version-21
      - build:
          name: build-14
          docker-image: "circleci/node:14-browsers-legacy"
      - build:
          name: build-12
          docker-image: "circleci/node:12-browsers-legacy"
      - build:
          name: build-10
          docker-image: "circleci/node:10-browsers-legacy"
