# Via Getting Started info
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1
  node: circleci/node@3.0.0

# Based on source from https://circleci.com/orbs/registry/orb/circleci/node?version=3.0.0#commands-install-packages
# DEV: Was burning through time on features that felt experimental (orbs) so moving to more familiar setup
jobs:
  build:
    executor: node/default
    steps:
      - node/checkout
      - browser-tools/install-chrome
      - node/install-packages
      - run:
          name: Run NPM Tests
          command: npm test
